require 'stendhal/rake_task'
require 'stendhal/reporter'
require 'stendhal/exceptions'
require 'stendhal/matchers'
require 'stendhal/mocks'
require 'stendhal/example'
require 'stendhal/example_group'

require 'stendhal/core_ext/kernel'
require 'stendhal/core_ext/object'
require 'stendhal/dsl'
